"""Export final resume + metadata to resume-data.yaml for HTML/PDF tooling."""
from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Optional


def _yaml_quote(s: str) -> str:
    if not s:
        return '""'
    if any(c in s for c in ':#[]{}&*!|>\'"\\'):
        escaped = s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
        return f'"{escaped}"'
    return s


def build_resume_data_yaml(
    final_resume: str,
    tailor_strategy: Optional[Dict[str, Any]] = None,
    summary_suggestion: Optional[Dict[str, Any]] = None,
    workflow_id: Optional[str] = None,
) -> str:
    """Build a minimal resume-data.yaml compatible with offer-toolkit HTML templates."""
    lines = [
        "# Auto-generated by AI Job Hunting Assistant",
        f"generated_at: {_yaml_quote(datetime.now().isoformat())}",
    ]
    if workflow_id:
        lines.append(f"workflow_id: {_yaml_quote(workflow_id)}")
    lines.append("final_resume: |")
    for line in (final_resume or "").splitlines():
        lines.append(f"  {line}")
    if tailor_strategy:
        lines.append("tailor_strategy:")
        for key in (
            "core_narrative_one_liner",
            "recommended_resume_version",
            "match_too_low_warning",
        ):
            val = tailor_strategy.get(key)
            if isinstance(val, str) and val.strip():
                lines.append(f"  {key}: {_yaml_quote(val.strip())}")
        for list_key in ("top_3_jd_keywords", "sections_to_emphasize", "sections_to_compress_or_remove"):
            items = tailor_strategy.get(list_key) or []
            if items:
                lines.append(f"  {list_key}:")
                for item in items:
                    if isinstance(item, str) and item.strip():
                        lines.append(f"    - {_yaml_quote(item.strip())}")
    if summary_suggestion and summary_suggestion.get("recommended_action") not in ("skip",):
        ss = summary_suggestion
        for key in ("suggested_headline", "suggested_summary"):
            val = ss.get(key)
            if isinstance(val, str) and val.strip():
                lines.append(f"{key}: {_yaml_quote(val.strip())}")
    return "\n".join(lines) + "\n"


def export_resume_data_yaml(
    final_resume: str,
    output_dir: Optional[str] = None,
    *,
    tailor_strategy: Optional[Dict[str, Any]] = None,
    summary_suggestion: Optional[Dict[str, Any]] = None,
    workflow_id: Optional[str] = None,
) -> Dict[str, Any]:
    """Write resume-data.yaml; default dir ~/Desktop/job-hunt."""
    base = Path(output_dir or Path.home() / "Desktop" / "job-hunt")
    base.mkdir(parents=True, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d-%H%M%S")
    path = base / f"resume-data-{ts}.yaml"
    content = build_resume_data_yaml(
        final_resume,
        tailor_strategy=tailor_strategy,
        summary_suggestion=summary_suggestion,
        workflow_id=workflow_id,
    )
    path.write_text(content, encoding="utf-8")
    return {"path": str(path), "format": "yaml"}
